//! POD5 File
//!
//! A POD5 file contains the data generated by a sequencing run. Data is
//! organized into tables, with each table containing batches of records.
//!
//! A file contains three tables:
//!
//! - run information, describing the sequencing run,
//! - reads, describing individual sequencing reads,
//! - signal, containing the raw electrical signal samples associated with reads.
//!
//! Each table is divided into batches, which contain groups of records. Batches
//! provide the unit of access for efficient reading and memory management.

pub mod table;
mod pod5;
mod run;
mod row_index;
pub(crate) mod distribution;
pub mod schema;

pub use self::{
    pod5::*,
    row_index::*,
    run::*
};


#[cfg(feature = "backend")]
pub mod backend {
    pub use self::super::{
        pod5::backend::*,
        run::backend::*,
    };
}